src/Entity/BdColec.php
<?php

namespace App\Entity;

use App\Repository\BdColecRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\Date;

/**
 * @ORM\Entity(repositoryClass=BdColecRepository::class)
 */
class BdColec
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $edition;

    /**
     * @ORM\Column(type="integer")
     */
    private $Tome;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity=Genres::class, inversedBy="bd")
     */
    private $genres;



    //public function __construct(Date $date)
//{
  //  $this->add_at = new \Date('now');
//}

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getEdition(): ?string
    {
        return $this->edition;
    }

    public function setEdition(?string $edition): self
    {
        $this->edition = $edition;

        return $this;
    }

    public function getTome(): ?int
    {
        return $this->Tome;
    }

    public function setTome(int $Tome): self
    {
        $this->Tome = $Tome;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getGenres(): ?Genres
    {
        return $this->genres;
    }

    public function setGenres(?Genres $genres): self
    {
        $this->genres = $genres;

        return $this;
    }


}

src/Controller/BdController.php
<?php

namespace App\Controller;

use App\Entity\BdColec;
use App\Entity\Genres;
use App\Form\AddBdCollectionType;
use App\Repository\BdColecRepository;
use Symfony\Bridge\Doctrine\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/bd", name="bd_")
 */

class BdController extends AbstractController
{
    /**
     * @Route("/collection", name="collection")
     */
    public function index(BdColecRepository $bdColecRepository): Response
    {
        $bdCollection= $bdColecRepository->findAll();
        return $this->render('bd/index.html.twig', [
            "bdCollections" => $bdCollection,
        ]);
    }
/**
 * @Route ("/addBd", name="add")
 */
    public function addBdCollection(\Symfony\Component\HttpFoundation\Request $request)
    {
        $bdCollection = new BdColec();
        $form = $this->createForm(AddBdCollectionType::class,$bdCollection);
        $form->handleRequest($request);
        $this->redirectToRoute('bd_add');
        if ($form->isSubmitted()) {
            $entityManager = $this->getDoctrine()->getManager();
           $entityManager->persist($bdCollection);
            $entityManager->flush();
            $this->addFlash('success', 'Votre BD a bien été ajoutée');

            return $this->redirectToRoute('bd_collection');
        }
        return $this->render('bd/add_bd.html.twig', [
            "form" => $form->createView(),
        ]);
    }

 /**
  * @Route ("/genre/{genres}" , name="genre" )
  */
    public function BdByGenres (
        ManagerRegistry $managerRegistry,
        BdColecRepository $bdColecRepository,
        Request $request,
        Genres $genres)
    {
        $bdColecRepository=$managerRegistry->getRepository(BdColec::class);
        $genres = $managerRegistry->getRepository(Genres::class);
        $genres = $request->get('name') ? $request->get('name') : '' ;
        $bds = [];
        if ($genres) {
            $bds = $bdColecRepository->findBy(['genre', $genres]);
        }
        return $this->render('bd/genre.html.twig',[
            'bds'=> $bds,
            'genres' => $managerRegistry->findAll()
        ]);
    }
}

templates/bd/add_bd.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<div class="d-flex justify-content-center my-3">
    <h1 class="col-10 bg-green text-black text-center p-2 m-3 rounded-3 fw-bold fs-3">Ajouter une nouvelle BD</h1>
</div>
<div class="justify-content-center col-10 mx-auto text-center">
    {{ form_start(form) }}
    {{ form_widget(form) }}
</div>
<div class="d-flex justify-content-center mt-4 mb-2 p-2">
    <button type="submit" class="btn btn-success text-light rounded-pill fw-bold fs-5">Valider</button>
</div>
{{ form_end(form) }}
{% endblock %}

templates/bd/genre.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BdController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Ma collection ✅</h1>

        <div class="card-group">
            {% for bdCollection in bdCollections %}
            <div class="card" style="width: 30%">
                <img src="{{ bdCollection.image }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ bdCollection.title }}</h5>
                    <li class="card-text">
                       Edition : {{ bdCollection.edition }}
                    </li>
                    <li class="card-text">
                       Tome : {{ bdCollection.tome }}
                    </li>
                    <li class="card-text">
                       Genre : {{ bdCollection.genres.name }}
                    </li>

                    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>
    <ul>
        <li></li>


    </ul>
</div>
{% endblock %}

templates/bd/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BdController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Ma collection ✅</h1>

        <div class="card-group">
            {% for bdCollection in bdCollections %}
            <div class="card" style="width: 30%">
                <img src="{{ bdCollection.image }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ bdCollection.title }}</h5>
                    <li class="card-text">
                       Edition : {{ bdCollection.edition }}
                    </li>
                    <li class="card-text">
                       Tome : {{ bdCollection.tome }}
                    </li>
                    <li class="card-text">
                       Genre : {{ bdCollection.genres.name}}
                    </li>

                    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>
    <ul>
        <li></li>


    </ul>
</div>
{% endblock %}